require:
  - rubocop-performance
  - rubocop-rails

Metrics/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent
