require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - ./db/schema.rb
    - lib/tasks/one_offs/migrate_steps_and_ingredients.rake

Metrics/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent

Metrics/BlockLength:
  Exclude:
    - ./**/*_spec*.rb
    - config/routes.rb

Metrics/ClassLength:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Rails/DynamicFindBy:
  Whitelist:
    - find_by_gql_id
    - find_by_gql_ids
